HOST = 'localhost'
PORT = 5000

NUM_BOTS = 50
NUM_EPISDOES = 1000


EPISODE_NUM_STEPS_MIN = 100
EPISODE_NUM_STEPS_MAX = 200

BOUNDSX = (2676, 2776)
BOUNDSY = (3428, 3528)

X_SIZE = BOUNDSX[1] - BOUNDSX[0]
Y_SIZE = (BOUNDSY[1] - BOUNDSY[0])



NODES_RANGE = 5
STATE_SIZE = 3 + (NODES_RANGE*2 + 1)** 2 #x,y,free space, nearby nodes

#STATE_SIZE = X_SIZE * Y_SIZE
ACTION_SIZE = 8 #move in each direction, interact in each direction

SPAWN_LOCATION = (2728, 3479)

RELATIVE_SPAWN_LOCATION = (SPAWN_LOCATION[0] - BOUNDSX[0], SPAWN_LOCATION[1] - BOUNDSY[0])

GOAL_LOC = (2724, 3493)
RELATIVE_GOAL_LOC = (GOAL_LOC[0] - BOUNDSX[0], GOAL_LOC[1] - BOUNDSY[0])

MODEL_SAVE_PATH = "./models/model.pt"

